---
title: "Base map for individual reefs"
aauthor: "Ben Cresswell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
 html_document:
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 4
    fig_width: 4
    highlight: textmate
    theme: spacelab
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#rm(list=ls())
getwd()
```


# Load required packages
```{r packages, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(sp)
library(rgdal)
library(rgeos)
library(adehabitatHR)
library(leaflet)
library(ggmap)    # for fortifying shapefiles
library(readxl)
library(scatterpie)
library(collapse)
library(tidyverse)
```

# First need to specify data from which to draw Osprey Reef area data:
```{r read-osprey-data, message=FALSE, warning=FALSE}
osprey_reef <- 
  readOGR("../data/3dgbr_geomorph/shape", "coralsea_dryreef") %>% 
  fortify() %>% 
  filter(long < 147) %>% 
  filter(lat > -14.1)
```

# And now can plot base map
```{r}
osprey_base <- 
  osprey_reef %>%   
  ggplot() +
  geom_polygon(aes(x = long, y = lat, group = group), color = 'grey30', fill = 'grey', lwd = 0.3) +
  coord_map(orientation = c(90,0, 150), ylim = c(-14.1, -13.75), xlim = c(146.5, 146.75)) +
  theme(axis.title = element_blank(), 
        #axis.text = element_blank(),
        #axis.ticks = element_blank(),
        #panel.grid = element_line(colour = "#ECEFF1"),
        panel.border = element_rect(colour = "black", fill = "transparent"),
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", colour = "transparent")) 

osprey_base
```







```{r}
osprey_zoom <- 
  osprey_reef %>%   
  ggplot() +
  geom_polygon(aes(x = long, y = lat, group = group), color = 'grey30', fill = 'grey', lwd = 0.3) +
  coord_map(orientation = c(90,0, 150), ylim = c(-13.91, -13.79), xlim = c(146.5, 146.61)) +
  theme(axis.title = element_blank(), 
        #axis.text = element_blank(),
        #axis.ticks = element_blank(),
        #panel.grid = element_line(colour = "#ECEFF1"),
        panel.border = element_rect(colour = "black", fill = "transparent"),
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", colour = "transparent")) 

osprey_zoom
```


## Receiver locations

```{r}
library(readxl)
site_list <- read_excel("../data/receiver_list_dep1.xlsx") %>% 
  mutate_if(is.character, as.factor)

site_list <- site_list %>%   
  dplyr::select(station_name, station_name_long, station_latitude, station_longitude)
```

## If we want separate locations for labels:
```{r}
site_list <-
  site_list %>% 
  mutate(label_long = 146.52,
         label_lat = station_latitude*1.001)
site_list
```

## Or can plot text within circles (points)
First need to shorten labels
```{r}
site_list <-
  site_list %>% 
  mutate(station_name = str_sub(station_name, 4, -1))
site_list
```



## Plot
```{r osprey-sites}
osprey_vr2s <- 
  osprey_zoom +
  geom_point(data = site_list, aes(x = station_longitude, y =station_latitude), colour = 'grey10', fill = 'lightskyblue', size = 6,  stroke = 0.3, shape = 21 )+
  geom_text(data = site_list, aes(x = station_longitude, y =station_latitude, label = station_name), size = 3) +
   annotate("text", x = 146.5, y = -13.79, label = "Osprey Reef - VR2W locations", 
           colour = "black", size = 5, fontface = 2, family = "Helvetica", hjust = 0)
ggsave(osprey_vr2s, filename = '../output/receivers_osprey.png', width = 200, height = 200, units = 'mm', dpi = 400)

```


# Add in tagging locations

```{r}
osprey_vr2s +
    geom_point(data = project_teleosts, aes(x = Long, y =Lat), colour = 'grey10', fill = 'black', size = 4,  stroke = 0.5, shape = 3 )
```





```{r}
ggsave()
```


